WEBDAV-22: Tomcat Xwiki 10.11 - 500 Error NoClassDefFoundError
- catch anything thrown in the finally block of the servlets
  "service" method so it does not shadow any actual error
  in the try-block